feature: cbi-726 test transfer all
Cerebellum-Network/cere-enterprise-smart-contracts pull request #18
Opened 2021-05-25 08:23 UTC by huythanhcere

Ticket ([url](https://cerenetwork.atlassian.net/browse/CBI-726))
Fix tests to confirm above.
Update add input fee for transfer all method.

2021-05-25 12:34 UTC, evgeny-s approved these changes
LGTM

2021-05-25 18:37 UTC, naure requested changes
Please add a test where transfer_all_balance is called from another account which is not owner. See how other tests use `set_caller` to do that.

2021-05-25 18:37 UTC, naure commented on cere02/lib.rs
> +        pub fn transfer_all_balance(&mut self, destination: AccountId, transaction_fee: Balance) -> Result<()> {
Where does this fee come from? Any documentation about that?

2021-05-25 18:37 UTC, naure commented on cere02/lib.rs
> +            let _result = self.env().transfer(destination, contract_bal - transaction_fee);
This does not check the result. There must be a `?` or an `unwrap` or `return Err`.

2021-05-26 03:23 UTC, huythanhcere commented on cere02/lib.rs
> +        pub fn transfer_all_balance(&mut self, destination: AccountId, transaction_fee: Balance) -> Result<()> {
This comment out of scope of the ticket. It is right. I will fix in next commit then tag you.

2021-05-26 03:24 UTC, huythanhcere commented
> Please add a test where transfer_all_balance is called from another account which is not owner. See how other tests use `set_caller` to do that.

This comment out of scope of the ticket. It is right. I will fix in next commit then tag you.

2021-05-26 03:42 UTC, huythanhcere commented on cere02/lib.rs
> +            let _result = self.env().transfer(destination, contract_bal - transaction_fee);
Result is unnecessary to check here. If error, token is not transferred.

2021-05-26 07:01 UTC, huythanhcere commented on cere02/lib.rs
> +            let _result = self.env().transfer(destination, contract_bal - transaction_fee);
Anw, i will fix this.

2021-05-31 12:35 UTC, naure approved these changes

2021-05-31 12:35 UTC, naure commented on cere02/lib.rs
> +        pub fn transfer_all_balance(&mut self, destination: AccountId, transaction_fee: Balance) -> Result<()> {
Ok I understand now. This is not a transaction fee, but the deposit for the contract storage that must stay on the contract account.

2021-05-31 15:09 UTC, merged