Add and list DDN nodes
Cerebellum-Network/cere-enterprise-smart-contracts pull request #20
Opened 2021-05-26 13:39 UTC by doasync

2021-05-26 14:44 UTC, evgeny-s commented on cere02/lib.rs
> +        ddn_nodes: Vec<DDNNode>
Either change Name to DDCNode or just DDN.

2021-05-26 16:08 UTC, doasync commented on cere02/lib.rs
> +        ddn_nodes: Vec<DDNNode>
I assumed DDN stands for "decentralized data network" ([source](https://blog.cere.network/cere-is-here-the-future-of-customer-data/)). Yeah, let's call them DDC nodes.

2021-05-26 18:21 UTC, doasync commented
Do we need an event `DDCNodeAdded`?

2021-05-27 08:38 UTC, evgeny-s commented
> Do we need an event DDCNodeAdded?
Yes, let's keep it

2021-05-27 08:42 UTC, naure requested changes
Nice work.

Let’s complete it right away with:
- Change to only_admin
- `remove_` and `is_` functions.
- Events for Add / Remove.

Basically the same as for reporters.
You may also move the code just after the "Admin: Reporters" section to show that it is similar.

2021-05-27 08:42 UTC, naure commented on cere02/lib.rs
> +        id: String,
Please rename everywhere `id` to `p2p_id`, to not confuse with account ID. (refers to [libp2p](https://docs.libp2p.io/concepts/peer-id/))

2021-05-27 08:42 UTC, naure commented on cere02/lib.rs
> +            self.only_reporter(&reporter)?;
This should be managed by the admin for now, not reporters.

2021-05-27 14:44 UTC, doasync commented on cere02/lib.rs
> +        id: String,
done

2021-05-27 14:45 UTC, doasync commented on cere02/lib.rs
> +            self.only_reporter(&reporter)?;
done

2021-05-27 14:49 UTC, doasync commented
@naure Thanks for your comments. I have updated the code:
- implemented emitting of add/remove events
- implemented `remove_` and `is_` functions
- set only_owner for add/remove
- renamed ddc node id to p2p_id
- moved ddc nodes code after the reporters
- refactored code

2021-05-28 12:52 UTC, naure approved these changes
Just one more request.

Great job.

2021-05-28 12:52 UTC, naure commented on cere02/lib.rs
> +        p2p_id: String,
There should be `url` too.

2021-05-28 12:52 UTC, naure commented on cere02/lib.rs
> +        fn decode_event(event: &ink_env::test::EmittedEvent) -> Event {
Good idea.

2021-05-28 13:58 UTC, doasync commented on cere02/lib.rs
> +        p2p_id: String,
[done](https://github.com/Cerebellum-Network/cere-enterprise-smart-contracts/pull/20/files#diff-a99b45b57bfdc35f8b28ef154fa4418c459a459aa60dfe0f98d8a350a93fa067R508)

2021-05-28 14:03 UTC, merged