updating transfer logic and refund functionality
Cerebellum-Network/cere-enterprise-smart-contracts pull request #3
Opened 2021-01-12 13:22 UTC by karthikeyan-cere

1. Updated transfer login (distributed accounts --> users --> distributed accounts).
2. Refund transaction fee for the transfer functions.
3. Updated the unit test.

2021-01-12 16:15 UTC, evgeny-s approved these changes

2021-01-12 16:15 UTC, evgeny-s commented
I love the part with unit tests specifically! Good job!

2021-01-13 09:17 UTC, huythanhcere requested changes
@karthikeyan-cere i have 2 comments. Please check.
cc: @evgeny-s @shivamcere

2021-01-13 09:17 UTC, huythanhcere commented on cere01/lib.rs
> +            if is_from_ds || is_to_ds {
This modification of  "if" should be kept for early return like the old process "if !ds_account_list.contains(&from) {
                self.env().emit_event(ErrorDS {" @karthikeyan-cere . Because not return early so that there are a lot of change.

2021-01-13 09:17 UTC, huythanhcere commented on cere01/lib.rs
> +                .expect("Off-chain environment should have been initialized already")
Is this RE relation to Off-chain environment? @karthikeyan-cere

2021-01-13 09:26 UTC, evgeny-s commented on cere01/lib.rs
> +            if is_from_ds || is_to_ds {
What do you mean @huythanhcere ?
Could you add more clarity?
Here we check either from or to account in distribution list. 
In the previous implementation, we had to add users to the distribution list which is wrong.

2021-01-13 09:28 UTC, evgeny-s commented on cere01/lib.rs
> +                .expect("Off-chain environment should have been initialized already")
I suppose this is a helper function for testing. 
@karthikeyan-cere , please confirm

2021-01-13 09:54 UTC, karthikeyan-cere commented on cere01/lib.rs
> +            if is_from_ds || is_to_ds {
@huythanhcere I believe this change will not impact much in our computation.

2021-01-13 09:54 UTC, karthikeyan-cere commented on cere01/lib.rs
> +                .expect("Off-chain environment should have been initialized already")
Yes, It will enable the default accounts.

2021-01-13 10:10 UTC, shivamcere commented on cere01/lib.rs
> +            if is_from_ds || is_to_ds {
You need to handle the if statement like how it was handled before, you need to emit the error if conditions are not met.

2021-01-13 10:19 UTC, merged